spring:
  application:
    name: chat-app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/chat_app?options=-c%20timezone=UTC
    username: postgres
    password: "120924"

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          type:
            json_format_mapper: com.learn.chat_app.configuration.CustomHibernateJsonFormatter

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: yfH1x5azlrE4we6XsVsZq3rd/0pdv15bm966IauAclguJzbzMEOspCAyoxHoVzfiKgn9d8eol5Qwk45Nw0qlpyDoDKKGByc6+Cz0yFRb9O0=